name: Thundra Artifact Uploader

on:
  workflow_dispatch:
  
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.thundra.me

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: |
          pip install codecov
          python scripts/ci/install
      #- run: npm config set registry ${{ secrets.THUNDRA_REGISTRY }}
      #- run: npm config set _auth ${{ secrets.THUNDRA_REGISTRY_AUTH }}
      - name: Run tests
        run: |
          python scripts/ci/run-tests --with-cov --with-xdist
      - name: Thundra Registry
        run: |
          npm config set registry ${{ secrets.THUNDRA_REGISTRY }}
          npm config set _auth ${{ secrets.THUNDRA_REGISTRY_AUTH }}
      - name: Foresight Action
        uses: thundra-io/foresight-test-kit-action@initial-action
        with:
          api_key: ${{ secrets.THUNDRA_APIKEY }}
          test_framework: pytest
          test_path: |
            ./tests/**
          cli_version: 213.2.7
